[package]
name = "color-ssh"
description = "A Rust-based SSH client with syntax highlighting."
version = "0.5.9"
edition = "2024"
authors = ["Karsyboy"]
documentation = "https://github.com/karsyboy/color-ssh"
readme = "README.md"
homepage = "https://github.com/karsyboy/color-ssh"
repository = "https://github.com/karsyboy/color-ssh"
license = "MIT"
keywords = ["ssh", "client", "syntax", "highlighting"]
categories = ["command-line-interface", "command-line-utilities", "network-programming"]

[[bin]]
name = "cossh"
path = "src/main.rs"

[lib]
name = "cossh"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.43"
clap = { version = "4.5.56", features = ["derive"] }
crossterm = { version = "0.29", features = ["osc52"] }
dirs = "6.0.0"
notify = "8.2.0"
once_cell = "1.21.3"
portable-pty = "0.8.1"
ratatui = "0.29.0"
regex = "1.12.2"
serde = {version ="1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
vt100 = "0.15.2"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

